rules = []
calendar_port = 8013
ui_port = 8013

[sources.from_1]
url = "http://localhost:8011/cal/out1.ics"
fetch_interval_minutes = 30
enabled = true

[sources.from_2]
url = "http://localhost:8012/cal/out2.ics"
fetch_interval_minutes = 30
enabled = true

[outputs.out3]
filter_by_category = []
exclude_category = []
include_sources = []
